name: master_test
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
    - uses: actions/checkout@master
    - run: apt install graphviz
    - run: go test -v.
